spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://公网ip:3306/sy_bs?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver
#开启驼峰命名规则
mybatis:
  configuration:
    map-underscore-to-camel-case: false
